name: Publish release APK

permissions:
  contents: write

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  package-release-apk:
    name: Generate and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          set -e
          chmod +x ./gradlew

      - name: Generate APK
        run: ./gradlew assembleRelease --stacktrace

      - name: ZipAlign & Sign APK
        id: sign_apk
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: 'app/release'
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
          zipAlign: true
      
      - name: Extract Version Number
        id: get_version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '"' | tr -d ',')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Create Version File
        run: echo "${{ env.VERSION_NAME }}" > latest-version.txt

      - name: SFTP Remote - Upload APK
        uses: wearesection/sftp-remote@1.0.1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          localPath: "${{ steps.sign_apk.outputs.signedReleaseFile }}"
          remotePath: "/var/www/html/apk/ZipStreams.apk" 
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }} 
          privateKeyIsFile: 'false'
      
      - name: SFTP Upload Version File
        uses: wearesection/sftp-remote@1.0.1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          localPath: "./latest-version.txt" 
          remotePath: "/var/www/html/apk/latest-version" 
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }} 
          privateKeyIsFile: 'false'
