name: Publish release APK

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          set -e
          chmod +x ./gradlew

      - name: Generate APK
        run: ./gradlew assembleRelease --stacktrace

      - name: ZipAlign & Sign APK
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
          zipAlign: true

      - name: SFTP Remote
        uses: wearesection/sftp-remote@1.0.1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          localPath: "./app/release/ZipStreams.apk" # Path to your APK
          remotePath: "/var/www/html/apk/ZipStreams.apk" # Remote directory and filename
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }} # Optional, use if using key-based authentication
          privateKeyIsFile: false # Set to true if the private key is stored as a file
