name: Publish release APK

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate and Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: |
          set -e
          chmod +x ./gradlew

      - name: Generate APK
        run: ./gradlew assembleRelease --stacktrace

      - name: ZipAlign & Sign APK
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
          zipAlign: true

      - name: SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ secrets.SFTP_SERVER }}
          user: ${{ secrets.SFTP_USER }}
          user_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local: "./app/release/ZipStreams.apk" # Path to your APK
          remote: "/var/www/html/apk/" # Remote directory where the APK should be uploaded
